{{- if .Values.clusterIssuer.enabled }}
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ .Values.clusterIssuer.name | quote }}
spec:
  acme:
    email: {{ .Values.clusterIssuer.email | quote }}
    server: {{ .Values.clusterIssuer.server | quote }}
    privateKeySecretRef:
      name: {{ .Values.clusterIssuer.privateKeySecretRef.name | quote }}
    solvers:
      - http01:
          ingress:
            ingressClassName: {{ .Values.clusterIssuer.solvers.http01.ingress.ingressClassName | quote }}
{{- end }}
