---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name | default "myweb-2-secret" }}
  namespace: {{ .Values.secret.namespace | default "myweb-2" }}
type: Opaque
data:
  username: {{ .Values.secret.data.username | default "bXl1c2VybmFtZQ==" }}
  password: {{ .Values.secret.data.password | default "bXlwYXNzd29yZA==" }}
