---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp-main-prod
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: ssh://git@github.com/prince-espiot/private_test_deployment.git
    targetRevision: HEAD
    path: environments/prod
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true # delete resources that are not in the git repo
      selfHeal: true # recreate resources that are not in the git repo
      allowEmpty: false # do not allow empty repo
    syncOptions:
      - Validate=true
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true