---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp-2
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: aputra/nginx-lesson159:~v0.4
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: ssh://git@github.com/prince-espiot/private_test_deployment.git
    targetRevision: main
    path: my-app-chart
    helm:
      parameters:
        - name: "replicaCount"
          value: "2"
        - name: "image.repository"
          value: okumop/myweb
        - name: "image.tag"
          value: v0.0.14
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - Validate=true
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true