apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  labels:
    app.kubernetes.io/instance: myweb-2
namespace: myweb-2
resources:
  - ../../../nginx-deployment-test
images:
  - name: okumop/myweb
    newTag: v0.0.19  # Update the image tag
