---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp-2
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: okumop/myweb:~v0.1
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: ssh://git@github.com:prince-espiot/private_test_deployment.git
    targetRevision: main
    path: environments/staging/myapp
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - Validate=true
      - CreateNamespace=false
      - PrunePropagationPolicy=foreground
      - PruneLast=true